// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetWorkingDirectory():Promise<string>;

export function GitDiff(arg1:string,arg2:string,arg3:string):Promise<string>;

export function GitDiffBranches(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function SetWorkingDirectory(arg1:string):Promise<void>;
