// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetWorkingDirectory() {
  return window['go']['main']['App']['GetWorkingDirectory']();
}

export function GitDiff(arg1, arg2, arg3) {
  return window['go']['main']['App']['GitDiff'](arg1, arg2, arg3);
}

export function GitDiffBranches(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GitDiffBranches'](arg1, arg2, arg3, arg4);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function SetWorkingDirectory(arg1) {
  return window['go']['main']['App']['SetWorkingDirectory'](arg1);
}
