// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyChangeToJson(arg1, arg2, arg3) {
  return window['go']['main']['App']['ApplyChangeToJson'](arg1, arg2, arg3);
}

export function CheckAlreadyApplied(arg1, arg2) {
  return window['go']['main']['App']['CheckAlreadyApplied'](arg1, arg2);
}

export function GetAppliedChangesAsJson(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetAppliedChangesAsJson'](arg1, arg2, arg3);
}

export function GetWorkingDirectory() {
  return window['go']['main']['App']['GetWorkingDirectory']();
}

export function GitDiff(arg1, arg2, arg3) {
  return window['go']['main']['App']['GitDiff'](arg1, arg2, arg3);
}

export function GitDiffBranches(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GitDiffBranches'](arg1, arg2, arg3, arg4);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function OpenDirectoryDialog(arg1) {
  return window['go']['main']['App']['OpenDirectoryDialog'](arg1);
}

export function OpenFileDialog(arg1, arg2, arg3) {
  return window['go']['main']['App']['OpenFileDialog'](arg1, arg2, arg3);
}

export function ParseDiffFile(arg1) {
  return window['go']['main']['App']['ParseDiffFile'](arg1);
}

export function ParseDiffToStandardChanges(arg1) {
  return window['go']['main']['App']['ParseDiffToStandardChanges'](arg1);
}

export function ReadJsonFile(arg1) {
  return window['go']['main']['App']['ReadJsonFile'](arg1);
}

export function ReadTextFile(arg1) {
  return window['go']['main']['App']['ReadTextFile'](arg1);
}

export function SaveAppliedChanges(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SaveAppliedChanges'](arg1, arg2, arg3, arg4);
}

export function SaveFileDialog(arg1, arg2) {
  return window['go']['main']['App']['SaveFileDialog'](arg1, arg2);
}

export function SaveTextFile(arg1, arg2) {
  return window['go']['main']['App']['SaveTextFile'](arg1, arg2);
}

export function SetWorkingDirectory(arg1) {
  return window['go']['main']['App']['SetWorkingDirectory'](arg1);
}

export function WriteJsonFile(arg1, arg2) {
  return window['go']['main']['App']['WriteJsonFile'](arg1, arg2);
}
