// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ApplyChangeToJson(arg1:string,arg2:main.DiffChange,arg3:string):Promise<void>;

export function CheckAlreadyApplied(arg1:string,arg2:Array<main.DiffChange>):Promise<Array<boolean>>;

export function CreateBackupFile(arg1:string):Promise<string>;

export function DeleteFile(arg1:string):Promise<void>;

export function GetAppliedChangesAsJson(arg1:string,arg2:Array<main.DiffChange>,arg3:Record<string, string>):Promise<string>;

export function GetWorkingDirectory():Promise<string>;

export function GitDiff(arg1:string,arg2:string,arg3:string):Promise<string>;

export function GitDiffBranches(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function OpenDirectoryDialog(arg1:string):Promise<string>;

export function OpenFileDialog(arg1:string,arg2:string,arg3:string):Promise<string>;

export function ParseDiffFile(arg1:string):Promise<Array<main.DiffChange>>;

export function ParseDiffToStandardChanges(arg1:string):Promise<Array<main.StandardizedDiffChange>>;

export function ReadJsonFile(arg1:string):Promise<Record<string, any>>;

export function ReadTextFile(arg1:string):Promise<string>;

export function RestoreFileFromBackup(arg1:string,arg2:string):Promise<void>;

export function SaveAppliedChanges(arg1:string,arg2:Array<main.DiffChange>,arg3:Record<string, string>,arg4:string):Promise<void>;

export function SaveFileDialog(arg1:string,arg2:string):Promise<string>;

export function SaveTextFile(arg1:string,arg2:string):Promise<void>;

export function SetWorkingDirectory(arg1:string):Promise<void>;

export function WriteJsonFile(arg1:string,arg2:Record<string, any>):Promise<void>;
